# SSL bump rules (compatible con Squid 6.x)
#ssl_bump peek all
#ssl_bump bump all


acl myprofile2 dstdomain  "/etc/squid/conf.d/domain_list/example_list.txt"
acl myprofile1   dstdomain       "/etc/squid/conf.d/domain_list/example_list.txt"

# --- SSL bump unificado ---
# Paso 1: mirar el SNI en todas las conexiones
ssl_bump peek all

# Paso 2: forzar bump en todo
ssl_bump bump all



#ssl_bump peek nobump_server
#ssl_bump splice nobump_server
#ssl_bump bump all

#