#policies.conf
# Deny requests to certain unsafe ports
http_access deny !Safe_ports

# Deny CONNECT to other than secure SSL ports
http_access deny CONNECT !SSL_ports

#policies
http_access deny myprofile1 myiplist

# And finally deny all other access to this proxy
http_access allow all








#