const SYSTEM_LOGGING_CHOICES = { sizes: ["10M", "25M", "50M", "100M", "250M", "500M", "1G", "2G"], retention: ["1day", "3day", "7day", "14day", "30day"], rotation: ["daily", "weekly"] };
const SYSTEM_LOGGING_FIELDS = [
  { section: "journald", key: "system_max_use", label: "Journal: tamaño máximo persistente", type: "select", choices: "sizes" },
  { section: "journald", key: "system_keep_free", label: "Journal: espacio libre protegido", type: "select", choices: "sizes" },
  { section: "journald", key: "runtime_max_use", label: "Journal: tamaño máximo runtime", type: "select", choices: "sizes" },
  { section: "journald", key: "max_retention_sec", label: "Journal: retención máxima", type: "select", choices: "retention" },
  { section: "journald", key: "compress", label: "Journal: comprimir", type: "checkbox" },
  { section: "system_logs", key: "enabled", label: "Logs Ubuntu: aplicar rotación", type: "checkbox" },
  { section: "system_logs", key: "rotation", label: "Logs Ubuntu: frecuencia", type: "select", choices: "rotation" },
  { section: "system_logs", key: "rotate", label: "Logs Ubuntu: rotaciones", type: "number", min: 1, max: 30 },
  { section: "system_logs", key: "maxsize", label: "Logs Ubuntu: tamaño máximo", type: "select", choices: "sizes" },
  { section: "system_logs", key: "compress", label: "Logs Ubuntu: comprimir", type: "checkbox" },
  { section: "system_logs", key: "delaycompress", label: "Logs Ubuntu: retrasar compresión", type: "checkbox" },
  { section: "nftables_logs", key: "enabled", label: "Logs nftables: activar archivo dedicado", type: "checkbox" },
  { section: "nftables_logs", key: "size", label: "Logs nftables: tamaño máximo", type: "select", choices: "sizes" },
  { section: "nftables_logs", key: "rotate", label: "Logs nftables: rotaciones", type: "number", min: 1, max: 30 },
  { section: "nftables_logs", key: "compress", label: "Logs nftables: comprimir", type: "checkbox" },
  { section: "nftables_logs", key: "delaycompress", label: "Logs nftables: retrasar compresión", type: "checkbox" }
];
function setSystemLoggingStatus(message, isError = false) { const status = document.getElementById("system-logging-status"); if (!status) return; status.textContent = message; status.className = isError ? "settings-status error" : "settings-status success"; }
function createSystemLoggingInput(field, value) { let input; if (field.type === "select") { input = document.createElement("select"); SYSTEM_LOGGING_CHOICES[field.choices].forEach(choice => { const option = document.createElement("option"); option.value = choice; option.textContent = choice; if (choice === value) option.selected = true; input.appendChild(option); }); } else if (field.type === "checkbox") { input = document.createElement("input"); input.type = "checkbox"; input.checked = Boolean(value); } else { input = document.createElement("input"); input.type = "number"; input.min = field.min; input.max = field.max; input.value = value; } input.dataset.section = field.section; input.dataset.key = field.key; input.className = "modal-input"; return input; }
function renderSystemLoggingForm(config) { const form = document.getElementById("system-logging-form"); form.innerHTML = ""; const groups = { journald: "Journal systemd", system_logs: "Logs clásicos de Ubuntu", nftables_logs: "Logs nftables Praesidium" }; Object.entries(groups).forEach(([section, title]) => { const fieldset = document.createElement("fieldset"); fieldset.className = "settings-fieldset"; const legend = document.createElement("legend"); legend.textContent = title; fieldset.appendChild(legend); SYSTEM_LOGGING_FIELDS.filter(field => field.section === section).forEach(field => { const wrapper = document.createElement("div"); wrapper.className = "modal-input-group"; const label = document.createElement("label"); label.className = "modal-prefix"; label.textContent = field.label; wrapper.appendChild(label); wrapper.appendChild(createSystemLoggingInput(field, config[field.section][field.key])); fieldset.appendChild(wrapper); }); form.appendChild(fieldset); }); const save = document.createElement("button"); save.type = "button"; save.className = "save-btn"; save.textContent = "Guardar candidate"; save.addEventListener("click", saveSystemLoggingConfig); form.appendChild(save); }
function collectSystemLoggingConfig() { const config = { journald: {}, system_logs: {}, nftables_logs: {} }; document.querySelectorAll("#system-logging-form input, #system-logging-form select").forEach(input => { const section = input.dataset.section; const key = input.dataset.key; if (!section || !key) return; if (input.type === "checkbox") config[section][key] = input.checked; else if (input.type === "number") config[section][key] = parseInt(input.value, 10); else config[section][key] = input.value; }); return config; }
function loadSystemLoggingConfig() { fetch("/system/logging/get_system_logging.php").then(response => response.json()).then(data => { if (data.error) { setSystemLoggingStatus(data.error, true); return; } renderSystemLoggingForm(data.config); setSystemLoggingStatus("Configuración candidate cargada."); }).catch(error => setSystemLoggingStatus(`Error cargando configuración: ${error}`, true)); }
function saveSystemLoggingConfig() { fetch("/system/logging/update_system_logging.php", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": getCsrfToken() }, body: JSON.stringify({ config: collectSystemLoggingConfig() }) }).then(response => response.json()).then(data => { if (data.error) { setSystemLoggingStatus(data.error, true); return; } renderSystemLoggingForm(data.config); setSystemLoggingStatus("Configuración guardada en candidate. Aplique Commit para pasarla a running."); }).catch(error => setSystemLoggingStatus(`Error guardando configuración: ${error}`, true)); }
loadSystemLoggingConfig();
