#!/usr/bin/env python3
"""
Mapa de modulos para tests de PraesidiumFirewall.

Objetivo:
    Centralizar rutas esperadas por modulo para que los tests modulares sean
    consistentes y mantenibles.

Seguridad:
    Este archivo solo contiene metadatos estaticos; no modifica runtime.
"""
MODULES = {'nftables': {'module_path': 'modern_format/modules/policies',
              'dir': 'nftables_test',
              'forms': ['backend/checks/system_data/default_forms/forms_policies_nft.json'],
              'structures': ['backend/checks/system_data/default_tables_structure/structure_tables_policies.json'],
              'candidate': ['data/rules_nftables_human_viewer.json'],
              'running': [],
              'endpoints': ['web/policies/common_policy_actions_nft/get_table_structure.php',
                            'web/policies/common_policy_actions_nft/get_table_content.php',
                            'web/policies/common_policy_actions_nft/get_forms_from_table.php',
                            'web/policies/common_policy_actions_nft/get_update_policy.php',
                            'web/policies/common_policy_actions_nft/get_delete_policy.php',
                            'web/policies/common_policy_actions_nft/validation_policy.php'],
              'backend': ['backend/commits/commit_task/convert_nftables.py',
                          'backend/commits/commit_task/task_gen_nftables_policies.py',
                          'backend/commits/commit_task/task_apply_nftables_policies.py'],
              'expected_keys': ['input', 'output', 'FORWARDING', 'PREROUTING', 'POSTROUTING'],
              'validation_terms': ['port', 'protocol', 'alias', 'icmp', 'cidr']},
 'bpfilter': {'module_path': 'modern_format/modules/policies',
              'dir': 'bpfilter_test',
              'forms': ['backend/checks/system_data/default_forms/forms_policies_bpf.json'],
              'structures': ['backend/checks/system_data/default_tables_structure/structure_tables_policies_bpf.json'],
              'candidate': ['data/rules_bpfilter_human_viewer.json'],
              'running': [],
              'endpoints': ['web/policies/common_policy_actions_bpf/get_table_structure.php',
                            'web/policies/common_policy_actions_bpf/get_table_content.php',
                            'web/policies/common_policy_actions_bpf/get_forms_from_table.php',
                            'web/policies/common_policy_actions_bpf/get_update_policy.php',
                            'web/policies/common_policy_actions_bpf/get_delete_policy.php',
                            'web/policies/common_policy_actions_bpf/validation_policy.php'],
              'backend': ['backend/commits/commit_task/convert_bpfilter.py',
                          'backend/commits/commit_task/task_gen_bpfilter_policies.py',
                          'backend/commits/commit_task/task_apply_bpfilter_policies.py'],
              'expected_keys': ['BF_HOOK_XDP', 'BF_HOOK_TC_INGRESS', 'BF_HOOK_TC_EGRESS'],
              'validation_terms': ['hook', 'iface', 'port', 'protocol', 'alias']},
 'dnsmasq': {'module_path': 'modern_format/modules/networking',
              'dir': 'dnsmasq_test',
             'forms': ['backend/checks/system_data/default_forms/forms_dhcp.json'],
             'structures': ['backend/checks/system_data/default_tables_structure/structure_table_dhcp.json'],
             'candidate': ['data/dhcp.json'],
             'running': ['data_running/dhcp.json'],
             'endpoints': ['web/networking/dhcp_table/get_table_structure.php',
                           'web/networking/dhcp_table/get_table_content.php',
                           'web/networking/dhcp_table/get_forms_from_table.php',
                           'web/networking/dhcp_table/get_update_dhcp.php',
                           'web/networking/dhcp_table/get_delete_dhcp.php',
                           'web/networking/dhcp_table/validation_dhcp.php'],
             'backend': ['backend/commits/commit_task/task_gen_dhcp_config.py',
                         'backend/commits/commit_task/task_apply_dhcp_config.py'],
             'expected_keys': ['dhcp'],
             'validation_terms': ['dnsmasq', 'lease', 'range', 'interface', 'network']},
 'services': {'module_path': 'modern_format/modules/system',
              'dir': 'services_test',
              'forms': ['backend/checks/system_data/default_forms/forms_services.json'],
              'structures': ['backend/checks/system_data/default_tables_structure/structure_table_services.json'],
              'candidate': ['data/services.json'],
              'running': ['data_running/services.json'],
              'endpoints': ['web/system/services/services_table/get_table_structure.php',
                            'web/system/services/services_table/get_table_content.php',
                            'web/system/services/services_table/get_forms_from_table.php',
                            'web/system/services/services_table/get_update.php',
                            'web/system/services/services_table/get_delete.php',
                            'web/system/services/services_table/get_runtime_status.php'],
              'backend': ['backend/commits/commit_task/task_apply_services.py'],
              'expected_keys': ['services'],
              'validation_terms': ['desired_enabled', 'configurable', 'systemctl', 'bpfilter', 'sysctl']},
 'wireguard': {'module_path': 'modern_format/modules/interfaces',
              'dir': 'wireguard_test',
               'forms': ['backend/checks/system_data/default_forms/forms_wireguard.json'],
               'structures': ['backend/checks/system_data/default_tables_structure/structure_table_wireguard.json'],
               'candidate': ['data/wireguard.json'],
               'running': ['data_running/wireguard.json'],
               'endpoints': ['web/interfaces/wireguard/remote_access_table/get_update.php',
                             'web/interfaces/wireguard/remote_access_table/get_delete.php',
                             'web/interfaces/wireguard/remote_access_table/get_table_content.php',
                             'web/interfaces/wireguard/remote_clients_table/get_update.php',
                             'web/interfaces/wireguard/remote_clients_table/get_delete.php',
                             'web/interfaces/wireguard/remote_clients_table/get_client_config.php',
                             'web/interfaces/wireguard/remote_clients_table/get_client_qr.php',
                             'web/interfaces/wireguard/site_to_site_table/get_update.php',
                             'web/interfaces/wireguard/site_to_site_table/get_delete.php'],
               'backend': ['backend/commits/commit_task/task_gen_wireguard_config.py',
                           'backend/commits/commit_task/task_apply_wireguard_config.py'],
               'expected_keys': ['wireguard_site_to_site', 'wireguard_remote_access', 'wireguard_remote_clients'],
               'validation_terms': ['private', 'public', 'allowed', 'endpoint', 'port']},
 'users': {'module_path': 'modern_format/modules/users',
              'dir': 'users_test',
           'forms': ['backend/checks/system_data/default_forms/forms_table_users.json'],
           'structures': ['backend/checks/system_data/default_tables_structure/structure_table_users.json'],
           'candidate': ['data/users.json'],
           'running': ['data_running/users.json'],
           'endpoints': ['web/users/users_table/get_table_structure.php',
                         'web/users/users_table/get_table_content.php',
                         'web/users/users_table/get_forms_from_table.php',
                         'web/users/users_table/get_update_user.php',
                         'web/users/users_table/get_delete_user.php',
                         'web/users/users_table/validation_user.php'],
           'backend': [],
           'expected_keys': ['table_users'],
           'validation_terms': ['user', 'user_pass', 'user_role', 'user_language']},
 'certificates': {'module_path': 'modern_format/modules/certificates',
              'dir': 'certificates_test',
                  'forms': ['backend/checks/system_data/default_forms/forms_certificates.json'],
                  'structures': ['backend/checks/system_data/default_tables_structure/structure_table_certificates.json'],
                  'candidate': [],
                  'running': [],
                  'endpoints': ['web/certificates/certificates_table/get_table_structure.php',
                                'web/certificates/certificates_table/get_table_content.php',
                                'web/certificates/certificates_table/get_forms_from_table.php',
                                'web/certificates/certificates_table/get_update_certificate.php',
                                'web/certificates/certificates_table/get_delete_certificates.php',
                                'web/certificates/certificates_table/get_download_certificate.php',
                                'web/certificates/certificates_table/validation_certificates.php'],
                  'backend': [],
                  'expected_keys': ['certificates'],
                  'validation_terms': ['certificate', 'openssl', 'name', 'expires']},
 'interfaces': {'module_path': 'modern_format/modules/interfaces',
              'dir': 'interfaces_test',
                'forms': ['backend/checks/system_data/default_forms/forms_interfaces.json'],
                'structures': ['backend/checks/system_data/default_tables_structure/structure_table_interfaces.json'],
                'candidate': [],
                'running': ['data_running/interfaces.json'],
                'endpoints': ['web/interfaces/interfaces_table/get_table_structure.php',
                              'web/interfaces/interfaces_table/get_table_content.php',
                              'web/interfaces/interfaces_table/get_forms_from_table.php',
                              'web/interfaces/interfaces_table/get_update_interface.php',
                              'web/interfaces/interfaces_table/get_delete_interface.php',
                              'web/interfaces/interfaces_table/validation_interface.php'],
                'backend': ['backend/commits/commit_task/task_gen_interface_config.py',
                            'backend/commits/commit_task/task_apply_interface_config.py'],
                'expected_keys': ['ethernets', 'bonds', 'bridges', 'vlans', 'wifis', 'wireguard'],
                'validation_terms': ['netplan', 'interface', 'address', 'gateway', 'mtu']},
 'monitor': {'module_path': 'modern_format/modules/monitor',
              'dir': 'monitor_test',
             'forms': ['backend/checks/system_data/default_forms/forms_monitor.json'],
             'structures': ['backend/checks/system_data/default_tables_structure/structure_table_monitor.json',
                            'backend/checks/system_data/default_tables_structure/structure_table_monitor_log.json'],
             'candidate': [],
             'running': [],
             'endpoints': ['web/monitor/logs_table/get_table_structure_monitor.php',
                           'web/monitor/logs_table/get_table_content_monitor.php',
                           'web/monitor/logs_table/get_table_structure_monitor_log.php',
                           'web/monitor/get_logs/get_logs.php'],
             'backend': ['backend/checks/check_monitor_log_extract/extract_monitor_log_nftables_for_get_user.py'],
             'expected_keys': ['Search_Filter'],
             'validation_terms': ['log', 'filter', 'protocol', 'nftables']},
 'system_logging': {'module_path': 'modern_format/modules/system',
              'dir': 'system_logging_test',
                    'forms': ['backend/checks/system_data/default_forms/forms_system_logging.json'],
                    'structures': ['backend/checks/system_data/default_tables_structure/structure_table_system_logging.json'],
                    'candidate': ['data/system_logging.json'],
                    'running': ['data_running/system_logging.json'],
                    'endpoints': ['web/system/logging/system_logging_table/get_table_structure.php',
                                  'web/system/logging/system_logging_table/get_table_content.php',
                                  'web/system/logging/system_logging_table/get_forms_from_table.php',
                                  'web/system/logging/system_logging_table/get_update_system_logging.php',
                                  'web/system/logging/system_logging_table/get_delete_system_logging.php'],
                    'backend': ['backend/commits/commit_task/task_apply_system_logging.py'],
                    'expected_keys': ['system_logging'],
                    'validation_terms': ['journald', 'logrotate', 'rsyslog', 'rotate']},
 'alias': {'module_path': 'modern_format/modules/alias',
              'dir': 'alias_test',
           'forms': ['backend/checks/system_data/default_forms/forms_alias.json'],
           'structures': ['backend/checks/system_data/default_tables_structure/structure_tables_alias.json'],
           'candidate': ['data/alias.json'],
           'running': [],
           'endpoints': ['web/alias/common_alias_actions/get_table_structure.php',
                         'web/alias/common_alias_actions/get_table_content.php',
                         'web/alias/common_alias_actions/get_forms_from_table.php',
                         'web/alias/common_alias_actions/update_alias.php',
                         'web/alias/common_alias_actions/delete_alias.php',
                         'web/alias/common_alias_actions/validation_alias.php'],
           'backend': [],
           'expected_keys': ['alias_address', 'alias_addr_group', 'alias_service', 'alias_service_group'],
           'validation_terms': ['alias', 'ip', 'port', 'group']}}
