<?php
require_once __DIR__ . '/common/security/auth.php';
require_login_page();
require_once __DIR__ . '/common/security/csrf.php';

// ES:
//     mainpage_pruebas.php es el shell experimental de Praesidium para validar
//     la generación modular de menús desde modules_web.json sin tocar todavía
//     el mainpage.php productivo.
// EN:
//     mainpage_pruebas.php is the experimental Praesidium shell used to validate
//     modular menu generation from modules_web.json without touching the current
//     production mainpage.php yet.
$username = $_SESSION['username'];
$role     = $_SESSION['role'];
$language = $_SESSION['language'] ?? 'es';

$langFile = __DIR__ . "/lang/{$language}.php";
if (!file_exists($langFile)) {
    $langFile = __DIR__ . "/lang/es.php";
}
$L = require $langFile;
$csrfToken = csrf_get_token();

// ES:
//     Escapa texto visible de forma uniforme para evitar repetir htmlspecialchars
//     en todos los puntos de renderizado del menú.
// EN:
//     Escape visible text consistently so htmlspecialchars is not repeated at
//     every menu rendering point.
function h($value): string
{
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

// ES:
//     Resuelve una clave de idioma usando el array $L actual.
//     Si falta la clave, devuelve la propia clave como fallback defensivo visible.
// EN:
//     Resolve a language key using the current $L array.
//     If the key is missing, return the key itself as a visible defensive fallback.
function lang_value(array $L, $key): string
{
    $key = (string)$key;
    return isset($L[$key]) ? (string)$L[$key] : $key;
}

// ES:
//     Carga el manifiesto Web generado por praesidium_modules_web_installer.py.
//     El fichero vive junto al mainpage para mantener juntos shell y contrato Web.
// EN:
//     Load the Web manifest generated by praesidium_modules_web_installer.py.
//     The file lives next to mainpage so the shell and Web contract stay together.
function load_modules_web_manifest(): array
{
    $manifestFile = __DIR__ . '/modules_web.json';
    if (!is_file($manifestFile)) {
        return [
            'menus' => [
                'top-menu' => [],
                'sidebar' => [],
            ],
        ];
    }

    $raw = file_get_contents($manifestFile);
    if ($raw === false) {
        return [
            'menus' => [
                'top-menu' => [],
                'sidebar' => [],
            ],
        ];
    }

    $decoded = json_decode($raw, true);
    if (!is_array($decoded)) {
        return [
            'menus' => [
                'top-menu' => [],
                'sidebar' => [],
            ],
        ];
    }

    if (!isset($decoded['menus']) || !is_array($decoded['menus'])) {
        $decoded['menus'] = [];
    }

    if (!isset($decoded['menus']['top-menu']) || !is_array($decoded['menus']['top-menu'])) {
        $decoded['menus']['top-menu'] = [];
    }

    if (!isset($decoded['menus']['sidebar']) || !is_array($decoded['menus']['sidebar'])) {
        $decoded['menus']['sidebar'] = [];
    }

    return $decoded;
}

// ES:
//     Renderiza el menú superior como enlaces planos, igual que mainpage.php.
//     top-menu no tiene summary ni bloques details.
// EN:
//     Render the top menu as flat links, just like mainpage.php.
//     top-menu has no summary and no details blocks.
function render_top_menu(array $modulesWeb, array $L): void
{
    $links = $modulesWeb['menus']['top-menu'] ?? [];
    ?>
    <div class="top-menu">
        <a href="#" data-page="home.php"><?= h(lang_value($L, 'menu_home')) ?></a>
        <?php foreach ($links as $link): ?>
            <?php
            if (!is_array($link)) {
                continue;
            }
            $dataPage = $link['dataPage'] ?? '';
            $keyLang = $link['keyLang'] ?? '';
            if (!is_string($dataPage) || $dataPage === '' || !is_string($keyLang) || $keyLang === '') {
                continue;
            }
            ?>
            <a href="#" data-page="<?= h($dataPage) ?>"><?= h(lang_value($L, $keyLang)) ?></a>
        <?php endforeach; ?>
        <a href="logout.php"><?= h(lang_value($L, 'menu_logout')) ?></a>
    </div>
    <?php
}

// ES:
//     Renderiza el menú lateral como bloques details/summary, igual que mainpage.php.
//     Las secciones ya llegan agrupadas desde modules_web.json.
// EN:
//     Render the sidebar menu as details/summary blocks, just like mainpage.php.
//     Sections already arrive grouped from modules_web.json.
function render_sidebar(array $modulesWeb, array $L): void
{
    $sections = $modulesWeb['menus']['sidebar'] ?? [];
    ?>
    <div class="sidebar">
        <?php foreach ($sections as $index => $section): ?>
            <?php
            if (!is_array($section)) {
                continue;
            }
            $summaryKey = $section['summary'] ?? '';
            $pages = $section['pages'] ?? [];
            if (!is_string($summaryKey) || $summaryKey === '' || !is_array($pages)) {
                continue;
            }
            ?>
            <details<?= $index === 0 ? ' open' : '' ?>>
                <summary><?= h(lang_value($L, $summaryKey)) ?></summary>
                <?php foreach ($pages as $page): ?>
                    <?php
                    if (!is_array($page)) {
                        continue;
                    }
                    $dataPage = $page['dataPage'] ?? '';
                    $keyLang = $page['keyLang'] ?? '';
                    if (!is_string($dataPage) || $dataPage === '' || !is_string($keyLang) || $keyLang === '') {
                        continue;
                    }
                    ?>
                    <a href="#" data-page="<?= h($dataPage) ?>"><?= h(lang_value($L, $keyLang)) ?></a>
                <?php endforeach; ?>
            </details>
        <?php endforeach; ?>
    </div>
    <?php
}

$modulesWeb = load_modules_web_manifest();
?>
<!DOCTYPE html>
<html lang="<?= h($language) ?>">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="<?= h($csrfToken) ?>">
    <title><?= h(lang_value($L, 'title')) ?></title>
    <link rel="stylesheet" href="styles.css">
    <link rel="icon" href="/logo/favicon.ico" sizes="any">
    <script src="/my_js/mainpage.js"></script>
    <script src="/my_js/generic_table.js"></script>
    <script src="/libraries/chart.umd.js"></script>
    <script src="/my_js/url_file_list.js"></script>
    <script src="/my_js/certs_table.js"></script>
</head>
<body>

    <div class="header-top">
        <img src="/logo/praesidium_logo_transparent_mini.png" alt="Praesidium Logo" class="header-logo">
        <div class="header-left">
            <h1><?= h(lang_value($L, 'title')) ?></h1>
            <h2><?= h(lang_value($L, 'welcome')) ?>, <?= h($username) ?>!</h2>
            <div class="user-info">
                <p><?= h(lang_value($L, 'role')) ?>: <?= h($role) ?></p>
                <p><?= h(lang_value($L, 'language')) ?>: <?= h($language) ?></p>
            </div>
        </div>
    </div>

    <?php render_top_menu($modulesWeb, $L); ?>

    <?php render_sidebar($modulesWeb, $L); ?>

    <div class="main-content" id="main-content">
        <p><?= h(lang_value($L, 'main_content')) ?></p>
    </div>

</body>
</html>
